server:
  port: 9000

spring:
  application:
    name: ecommerce-server
  datasource:
    url: jdbc:mysql://localhost:3307/ecommerce
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: always
      data-locations: classpath:/db/migration/data.sql
  flyway:
    enabled: false
    locations: classpath:/db/migration
    baseline-on-migrate: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-microservice-security-realms

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

management:
  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: always
    metrics:
      distribution:
        percentiles-histogram:
          http:
            server:
              requests: true

  observations:
    key-values:
      application: server
    tracing:
      sampling:
        probability: 1.0
    zipkin:
      tracing:
        endpoint: http://tempo:9411/api/v2/spans

#Loki URL
loki:
  url: http://localhost:3100/loki/api/v1/push
